//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project7DayAndNight.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFeatures
    {
        public int FeaturesId { get; set; }
        public string FeaturesTitle { get; set; }
        public string FeaturesDescription { get; set; }
        public string FeaturesIcon { get; set; }
    }
}
