//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project7DayAndNight.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSlider
    {
        public int SliderId { get; set; }
        public string SliderTitle { get; set; }
        public string SliderSubTitle1 { get; set; }
        public string SliderDescription { get; set; }
        public string SliderSubTitle2 { get; set; }
        public string SliderImage { get; set; }
    }
}
