//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project7DayAndNight.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblServices
    {
        public int ServicesId { get; set; }
        public string ServicesName { get; set; }
        public string ServicesDescription { get; set; }
        public string ServicesIcon { get; set; }
        public string ServicesImage { get; set; }
    }
}
